name: CI

# Runs on push, pull requests, and manual dispatch
on:
  push:
  pull_request:
  workflow_dispatch:

# Environment variables for Foundry
env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show versions
        run: |
          rustc --version
          cargo --version
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check

      - name: Run Forge tests
        run: |
          forge test -vvv

      - name: Run Cargo check
        run: |
          cargo check

      - name: Run Cargo tests
        run: |
          cargo test --verbose

      - name: Run Cargo clippy
        run: |
          cargo clippy -- -D warnings
